### ISSUE TITLE
where is the tab.lua

### ISSUE THREAD

**Issue by bswbatman** [TeamHG-Memex/scrash-lua-examples#1]
hi , 
After Readme , I need that 
`tab.lua`  not the public anymore?
thanks
fox

**Comment by lopuhin** [comment]
yes, ``tabs.lua`` was removed (you can still fetch it from history), I think its functionality (and all other scripts) was merged in the ``headless_horseman.lua``

**Comment by bswbatman** [comment]
Thank you

**Comment by bswbatman** [comment]
Thanks again, that help me

Konstantin Lopuhin <notifications@github.com> 于 2018年8月20日周一 下午7:27写道：
